# Generated by Django 3.2.5 on 2021-08-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210803_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
        migrations.RenameModel(
            old_name='Tutor',
            new_name='Tutor1',
        ),
    ]
