# Generated by Django 3.2.5 on 2021-08-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Pre_Requirment',
            new_name='Pre_Requirement',
        ),
    ]
